apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: podinfo
  name: podinfo
  namespace: team-base
spec:
  ports:
  - name: 9898-9898
    port: 80
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: LoadBalancer
status:
  loadBalancer: {}
